<?php
/**
 * CustomerSettingsResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DRACOON
 *
 * REST Web Services for DRACOON<br>Version: 4.14.4  - built at: 2019-11-04 11:46:45<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a>
 *
 * OpenAPI spec version: 4.14.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * CustomerSettingsResponse Class Doc Comment
 *
 * @category Class
 * @description Customer settings
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomerSettingsResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CustomerSettingsResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'home_rooms_active' => 'bool',
        'home_room_parent_id' => 'int',
        'home_room_parent_name' => 'string',
        'home_room_quota' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'home_rooms_active' => null,
        'home_room_parent_id' => 'int64',
        'home_room_parent_name' => null,
        'home_room_quota' => 'int64'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'home_rooms_active' => 'homeRoomsActive',
        'home_room_parent_id' => 'homeRoomParentId',
        'home_room_parent_name' => 'homeRoomParentName',
        'home_room_quota' => 'homeRoomQuota'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'home_rooms_active' => 'setHomeRoomsActive',
        'home_room_parent_id' => 'setHomeRoomParentId',
        'home_room_parent_name' => 'setHomeRoomParentName',
        'home_room_quota' => 'setHomeRoomQuota'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'home_rooms_active' => 'getHomeRoomsActive',
        'home_room_parent_id' => 'getHomeRoomParentId',
        'home_room_parent_name' => 'getHomeRoomParentName',
        'home_room_quota' => 'getHomeRoomQuota'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['home_rooms_active'] = isset($data['home_rooms_active']) ? $data['home_rooms_active'] : null;
        $this->container['home_room_parent_id'] = isset($data['home_room_parent_id']) ? $data['home_room_parent_id'] : null;
        $this->container['home_room_parent_name'] = isset($data['home_room_parent_name']) ? $data['home_room_parent_name'] : null;
        $this->container['home_room_quota'] = isset($data['home_room_quota']) ? $data['home_room_quota'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['home_rooms_active'] === null) {
            $invalidProperties[] = "'home_rooms_active' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets home_rooms_active
     *
     * @return bool
     */
    public function getHomeRoomsActive()
    {
        return $this->container['home_rooms_active'];
    }

    /**
     * Sets home_rooms_active
     *
     * @param bool $home_rooms_active Homerooms active
     *
     * @return $this
     */
    public function setHomeRoomsActive($home_rooms_active)
    {
        $this->container['home_rooms_active'] = $home_rooms_active;

        return $this;
    }

    /**
     * Gets home_room_parent_id
     *
     * @return int
     */
    public function getHomeRoomParentId()
    {
        return $this->container['home_room_parent_id'];
    }

    /**
     * Sets home_room_parent_id
     *
     * @param int $home_room_parent_id Homeroom Parent ID
     *
     * @return $this
     */
    public function setHomeRoomParentId($home_room_parent_id)
    {
        $this->container['home_room_parent_id'] = $home_room_parent_id;

        return $this;
    }

    /**
     * Gets home_room_parent_name
     *
     * @return string
     */
    public function getHomeRoomParentName()
    {
        return $this->container['home_room_parent_name'];
    }

    /**
     * Sets home_room_parent_name
     *
     * @param string $home_room_parent_name Homeroom Parent Name
     *
     * @return $this
     */
    public function setHomeRoomParentName($home_room_parent_name)
    {
        $this->container['home_room_parent_name'] = $home_room_parent_name;

        return $this;
    }

    /**
     * Gets home_room_quota
     *
     * @return int
     */
    public function getHomeRoomQuota()
    {
        return $this->container['home_room_quota'];
    }

    /**
     * Sets home_room_quota
     *
     * @param int $home_room_quota Homeroom Quota in bytes
     *
     * @return $this
     */
    public function setHomeRoomQuota($home_room_quota)
    {
        $this->container['home_room_quota'] = $home_room_quota;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


