<?php
/**
 * DownloadShare
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DRACOON
 *
 * REST Web Services for DRACOON<br>Version: 4.14.4  - built at: 2019-11-04 11:46:45<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a>
 *
 * OpenAPI spec version: 4.14.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * DownloadShare Class Doc Comment
 *
 * @category Class
 * @description Download Share information
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DownloadShare implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DownloadShare';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'name' => 'string',
        'node_id' => 'int',
        'access_key' => 'string',
        'notify_creator' => 'bool',
        'cnt_downloads' => 'int',
        'created_at' => '\DateTime',
        'created_by' => '\Swagger\Client\Model\UserInfo',
        'updated_at' => '\DateTime',
        'updated_by' => '\Swagger\Client\Model\UserInfo',
        'internal_notes' => 'string',
        'notes' => 'string',
        'show_creator_name' => 'bool',
        'show_creator_username' => 'bool',
        'is_protected' => 'bool',
        'expire_at' => '\DateTime',
        'max_downloads' => 'int',
        'node_path' => 'string',
        'data_url' => 'string',
        'is_encrypted' => 'bool',
        'classification' => 'int',
        'recipients' => 'string',
        'sms_recipients' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'int64',
        'name' => null,
        'node_id' => 'int64',
        'access_key' => null,
        'notify_creator' => null,
        'cnt_downloads' => 'int32',
        'created_at' => 'date-time',
        'created_by' => null,
        'updated_at' => 'date-time',
        'updated_by' => null,
        'internal_notes' => null,
        'notes' => null,
        'show_creator_name' => null,
        'show_creator_username' => null,
        'is_protected' => null,
        'expire_at' => 'date-time',
        'max_downloads' => 'int32',
        'node_path' => null,
        'data_url' => null,
        'is_encrypted' => null,
        'classification' => 'int32',
        'recipients' => null,
        'sms_recipients' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'node_id' => 'nodeId',
        'access_key' => 'accessKey',
        'notify_creator' => 'notifyCreator',
        'cnt_downloads' => 'cntDownloads',
        'created_at' => 'createdAt',
        'created_by' => 'createdBy',
        'updated_at' => 'updatedAt',
        'updated_by' => 'updatedBy',
        'internal_notes' => 'internalNotes',
        'notes' => 'notes',
        'show_creator_name' => 'showCreatorName',
        'show_creator_username' => 'showCreatorUsername',
        'is_protected' => 'isProtected',
        'expire_at' => 'expireAt',
        'max_downloads' => 'maxDownloads',
        'node_path' => 'nodePath',
        'data_url' => 'dataUrl',
        'is_encrypted' => 'isEncrypted',
        'classification' => 'classification',
        'recipients' => 'recipients',
        'sms_recipients' => 'smsRecipients'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'node_id' => 'setNodeId',
        'access_key' => 'setAccessKey',
        'notify_creator' => 'setNotifyCreator',
        'cnt_downloads' => 'setCntDownloads',
        'created_at' => 'setCreatedAt',
        'created_by' => 'setCreatedBy',
        'updated_at' => 'setUpdatedAt',
        'updated_by' => 'setUpdatedBy',
        'internal_notes' => 'setInternalNotes',
        'notes' => 'setNotes',
        'show_creator_name' => 'setShowCreatorName',
        'show_creator_username' => 'setShowCreatorUsername',
        'is_protected' => 'setIsProtected',
        'expire_at' => 'setExpireAt',
        'max_downloads' => 'setMaxDownloads',
        'node_path' => 'setNodePath',
        'data_url' => 'setDataUrl',
        'is_encrypted' => 'setIsEncrypted',
        'classification' => 'setClassification',
        'recipients' => 'setRecipients',
        'sms_recipients' => 'setSmsRecipients'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'node_id' => 'getNodeId',
        'access_key' => 'getAccessKey',
        'notify_creator' => 'getNotifyCreator',
        'cnt_downloads' => 'getCntDownloads',
        'created_at' => 'getCreatedAt',
        'created_by' => 'getCreatedBy',
        'updated_at' => 'getUpdatedAt',
        'updated_by' => 'getUpdatedBy',
        'internal_notes' => 'getInternalNotes',
        'notes' => 'getNotes',
        'show_creator_name' => 'getShowCreatorName',
        'show_creator_username' => 'getShowCreatorUsername',
        'is_protected' => 'getIsProtected',
        'expire_at' => 'getExpireAt',
        'max_downloads' => 'getMaxDownloads',
        'node_path' => 'getNodePath',
        'data_url' => 'getDataUrl',
        'is_encrypted' => 'getIsEncrypted',
        'classification' => 'getClassification',
        'recipients' => 'getRecipients',
        'sms_recipients' => 'getSmsRecipients'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const CLASSIFICATION_1 = 1;
    const CLASSIFICATION_2 = 2;
    const CLASSIFICATION_3 = 3;
    const CLASSIFICATION_4 = 4;
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getClassificationAllowableValues()
    {
        return [
            self::CLASSIFICATION_1,
            self::CLASSIFICATION_2,
            self::CLASSIFICATION_3,
            self::CLASSIFICATION_4,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['node_id'] = isset($data['node_id']) ? $data['node_id'] : null;
        $this->container['access_key'] = isset($data['access_key']) ? $data['access_key'] : null;
        $this->container['notify_creator'] = isset($data['notify_creator']) ? $data['notify_creator'] : null;
        $this->container['cnt_downloads'] = isset($data['cnt_downloads']) ? $data['cnt_downloads'] : null;
        $this->container['created_at'] = isset($data['created_at']) ? $data['created_at'] : null;
        $this->container['created_by'] = isset($data['created_by']) ? $data['created_by'] : null;
        $this->container['updated_at'] = isset($data['updated_at']) ? $data['updated_at'] : null;
        $this->container['updated_by'] = isset($data['updated_by']) ? $data['updated_by'] : null;
        $this->container['internal_notes'] = isset($data['internal_notes']) ? $data['internal_notes'] : null;
        $this->container['notes'] = isset($data['notes']) ? $data['notes'] : null;
        $this->container['show_creator_name'] = isset($data['show_creator_name']) ? $data['show_creator_name'] : null;
        $this->container['show_creator_username'] = isset($data['show_creator_username']) ? $data['show_creator_username'] : null;
        $this->container['is_protected'] = isset($data['is_protected']) ? $data['is_protected'] : null;
        $this->container['expire_at'] = isset($data['expire_at']) ? $data['expire_at'] : null;
        $this->container['max_downloads'] = isset($data['max_downloads']) ? $data['max_downloads'] : null;
        $this->container['node_path'] = isset($data['node_path']) ? $data['node_path'] : null;
        $this->container['data_url'] = isset($data['data_url']) ? $data['data_url'] : null;
        $this->container['is_encrypted'] = isset($data['is_encrypted']) ? $data['is_encrypted'] : null;
        $this->container['classification'] = isset($data['classification']) ? $data['classification'] : null;
        $this->container['recipients'] = isset($data['recipients']) ? $data['recipients'] : null;
        $this->container['sms_recipients'] = isset($data['sms_recipients']) ? $data['sms_recipients'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['node_id'] === null) {
            $invalidProperties[] = "'node_id' can't be null";
        }
        if ($this->container['access_key'] === null) {
            $invalidProperties[] = "'access_key' can't be null";
        }
        if ($this->container['notify_creator'] === null) {
            $invalidProperties[] = "'notify_creator' can't be null";
        }
        if ($this->container['cnt_downloads'] === null) {
            $invalidProperties[] = "'cnt_downloads' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['created_by'] === null) {
            $invalidProperties[] = "'created_by' can't be null";
        }
        $allowedValues = $this->getClassificationAllowableValues();
        if (!is_null($this->container['classification']) && !in_array($this->container['classification'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'classification', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id Share ID
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Alias name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets node_id
     *
     * @return int
     */
    public function getNodeId()
    {
        return $this->container['node_id'];
    }

    /**
     * Sets node_id
     *
     * @param int $node_id Source node ID
     *
     * @return $this
     */
    public function setNodeId($node_id)
    {
        $this->container['node_id'] = $node_id;

        return $this;
    }

    /**
     * Gets access_key
     *
     * @return string
     */
    public function getAccessKey()
    {
        return $this->container['access_key'];
    }

    /**
     * Sets access_key
     *
     * @param string $access_key Share access key to generate secure link
     *
     * @return $this
     */
    public function setAccessKey($access_key)
    {
        $this->container['access_key'] = $access_key;

        return $this;
    }

    /**
     * Gets notify_creator
     *
     * @return bool
     */
    public function getNotifyCreator()
    {
        return $this->container['notify_creator'];
    }

    /**
     * Sets notify_creator
     *
     * @param bool $notify_creator Notify creator on every download.
     *
     * @return $this
     */
    public function setNotifyCreator($notify_creator)
    {
        $this->container['notify_creator'] = $notify_creator;

        return $this;
    }

    /**
     * Gets cnt_downloads
     *
     * @return int
     */
    public function getCntDownloads()
    {
        return $this->container['cnt_downloads'];
    }

    /**
     * Sets cnt_downloads
     *
     * @param int $cnt_downloads Downloads counter (incremented on each download)
     *
     * @return $this
     */
    public function setCntDownloads($cnt_downloads)
    {
        $this->container['cnt_downloads'] = $cnt_downloads;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at Creation date
     *
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets created_by
     *
     * @return \Swagger\Client\Model\UserInfo
     */
    public function getCreatedBy()
    {
        return $this->container['created_by'];
    }

    /**
     * Sets created_by
     *
     * @param \Swagger\Client\Model\UserInfo $created_by Created by user
     *
     * @return $this
     */
    public function setCreatedBy($created_by)
    {
        $this->container['created_by'] = $created_by;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at Modification date
     *
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets updated_by
     *
     * @return \Swagger\Client\Model\UserInfo
     */
    public function getUpdatedBy()
    {
        return $this->container['updated_by'];
    }

    /**
     * Sets updated_by
     *
     * @param \Swagger\Client\Model\UserInfo $updated_by Modified by user
     *
     * @return $this
     */
    public function setUpdatedBy($updated_by)
    {
        $this->container['updated_by'] = $updated_by;

        return $this;
    }

    /**
     * Gets internal_notes
     *
     * @return string
     */
    public function getInternalNotes()
    {
        return $this->container['internal_notes'];
    }

    /**
     * Sets internal_notes
     *
     * @param string $internal_notes Internal notes (limited to 255 characters)
     *
     * @return $this
     */
    public function setInternalNotes($internal_notes)
    {
        $this->container['internal_notes'] = $internal_notes;

        return $this;
    }

    /**
     * Gets notes
     *
     * @return string
     */
    public function getNotes()
    {
        return $this->container['notes'];
    }

    /**
     * Sets notes
     *
     * @param string $notes User notes (limited to 255 characters)
     *
     * @return $this
     */
    public function setNotes($notes)
    {
        $this->container['notes'] = $notes;

        return $this;
    }

    /**
     * Gets show_creator_name
     *
     * @return bool
     */
    public function getShowCreatorName()
    {
        return $this->container['show_creator_name'];
    }

    /**
     * Sets show_creator_name
     *
     * @param bool $show_creator_name Show creator first and last name.
     *
     * @return $this
     */
    public function setShowCreatorName($show_creator_name)
    {
        $this->container['show_creator_name'] = $show_creator_name;

        return $this;
    }

    /**
     * Gets show_creator_username
     *
     * @return bool
     */
    public function getShowCreatorUsername()
    {
        return $this->container['show_creator_username'];
    }

    /**
     * Sets show_creator_username
     *
     * @param bool $show_creator_username Show creator email address.
     *
     * @return $this
     */
    public function setShowCreatorUsername($show_creator_username)
    {
        $this->container['show_creator_username'] = $show_creator_username;

        return $this;
    }

    /**
     * Gets is_protected
     *
     * @return bool
     */
    public function getIsProtected()
    {
        return $this->container['is_protected'];
    }

    /**
     * Sets is_protected
     *
     * @param bool $is_protected Is share protected by password
     *
     * @return $this
     */
    public function setIsProtected($is_protected)
    {
        $this->container['is_protected'] = $is_protected;

        return $this;
    }

    /**
     * Gets expire_at
     *
     * @return \DateTime
     */
    public function getExpireAt()
    {
        return $this->container['expire_at'];
    }

    /**
     * Sets expire_at
     *
     * @param \DateTime $expire_at Expiration date
     *
     * @return $this
     */
    public function setExpireAt($expire_at)
    {
        $this->container['expire_at'] = $expire_at;

        return $this;
    }

    /**
     * Gets max_downloads
     *
     * @return int
     */
    public function getMaxDownloads()
    {
        return $this->container['max_downloads'];
    }

    /**
     * Sets max_downloads
     *
     * @param int $max_downloads Max allowed downloads
     *
     * @return $this
     */
    public function setMaxDownloads($max_downloads)
    {
        $this->container['max_downloads'] = $max_downloads;

        return $this;
    }

    /**
     * Gets node_path
     *
     * @return string
     */
    public function getNodePath()
    {
        return $this->container['node_path'];
    }

    /**
     * Sets node_path
     *
     * @param string $node_path Path to shared download node
     *
     * @return $this
     */
    public function setNodePath($node_path)
    {
        $this->container['node_path'] = $node_path;

        return $this;
    }

    /**
     * Gets data_url
     *
     * @return string
     */
    public function getDataUrl()
    {
        return $this->container['data_url'];
    }

    /**
     * Sets data_url
     *
     * @param string $data_url Path to shared download node
     *
     * @return $this
     */
    public function setDataUrl($data_url)
    {
        $this->container['data_url'] = $data_url;

        return $this;
    }

    /**
     * Gets is_encrypted
     *
     * @return bool
     */
    public function getIsEncrypted()
    {
        return $this->container['is_encrypted'];
    }

    /**
     * Sets is_encrypted
     *
     * @param bool $is_encrypted Encrypted share (this only applies to shared files, not folders)
     *
     * @return $this
     */
    public function setIsEncrypted($is_encrypted)
    {
        $this->container['is_encrypted'] = $is_encrypted;

        return $this;
    }

    /**
     * Gets classification
     *
     * @return int
     */
    public function getClassification()
    {
        return $this->container['classification'];
    }

    /**
     * Sets classification
     *
     * @param int $classification Classification ID: * `1` - public * `2` - internal * `3` - confidential * `4` - strictly confidential  [Deprecated since version 4.11.0]
     *
     * @return $this
     */
    public function setClassification($classification)
    {
        $allowedValues = $this->getClassificationAllowableValues();
        if (!is_null($classification) && !in_array($classification, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'classification', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['classification'] = $classification;

        return $this;
    }

    /**
     * Gets recipients
     *
     * @return string
     */
    public function getRecipients()
    {
        return $this->container['recipients'];
    }

    /**
     * Sets recipients
     *
     * @param string $recipients `DEPRECATED`: CSV string of recipient email addresses  [Deprecated since version 4.11.0]
     *
     * @return $this
     */
    public function setRecipients($recipients)
    {
        $this->container['recipients'] = $recipients;

        return $this;
    }

    /**
     * Gets sms_recipients
     *
     * @return string
     */
    public function getSmsRecipients()
    {
        return $this->container['sms_recipients'];
    }

    /**
     * Sets sms_recipients
     *
     * @param string $sms_recipients `DEPRECATED`: CSV string of recipient MSISDNs  [Deprecated since version 4.11.0]
     *
     * @return $this
     */
    public function setSmsRecipients($sms_recipients)
    {
        $this->container['sms_recipients'] = $sms_recipients;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


