<?php
/**
 * SystemInfo
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DRACOON
 *
 * REST Web Services for DRACOON<br>Version: 4.14.4  - built at: 2019-11-04 11:46:45<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a>
 *
 * OpenAPI spec version: 4.14.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SystemInfo Class Doc Comment
 *
 * @category Class
 * @description System information (default language and authentication methods)
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SystemInfo implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SystemInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'language_default' => 'string',
        'hide_login_input_fields' => 'bool',
        's3_hosts' => 'string[]',
        'auth_methods' => '\Swagger\Client\Model\AuthMethod[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'language_default' => null,
        'hide_login_input_fields' => null,
        's3_hosts' => null,
        'auth_methods' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'language_default' => 'languageDefault',
        'hide_login_input_fields' => 'hideLoginInputFields',
        's3_hosts' => 's3Hosts',
        'auth_methods' => 'authMethods'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'language_default' => 'setLanguageDefault',
        'hide_login_input_fields' => 'setHideLoginInputFields',
        's3_hosts' => 'setS3Hosts',
        'auth_methods' => 'setAuthMethods'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'language_default' => 'getLanguageDefault',
        'hide_login_input_fields' => 'getHideLoginInputFields',
        's3_hosts' => 'getS3Hosts',
        'auth_methods' => 'getAuthMethods'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['language_default'] = isset($data['language_default']) ? $data['language_default'] : null;
        $this->container['hide_login_input_fields'] = isset($data['hide_login_input_fields']) ? $data['hide_login_input_fields'] : null;
        $this->container['s3_hosts'] = isset($data['s3_hosts']) ? $data['s3_hosts'] : null;
        $this->container['auth_methods'] = isset($data['auth_methods']) ? $data['auth_methods'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['language_default'] === null) {
            $invalidProperties[] = "'language_default' can't be null";
        }
        if ($this->container['hide_login_input_fields'] === null) {
            $invalidProperties[] = "'hide_login_input_fields' can't be null";
        }
        if ($this->container['s3_hosts'] === null) {
            $invalidProperties[] = "'s3_hosts' can't be null";
        }
        if ($this->container['auth_methods'] === null) {
            $invalidProperties[] = "'auth_methods' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets language_default
     *
     * @return string
     */
    public function getLanguageDefault()
    {
        return $this->container['language_default'];
    }

    /**
     * Sets language_default
     *
     * @param string $language_default System default language cf. [RFC 5646](https://tools.ietf.org/html/rfc5646)
     *
     * @return $this
     */
    public function setLanguageDefault($language_default)
    {
        $this->container['language_default'] = $language_default;

        return $this;
    }

    /**
     * Gets hide_login_input_fields
     *
     * @return bool
     */
    public function getHideLoginInputFields()
    {
        return $this->container['hide_login_input_fields'];
    }

    /**
     * Sets hide_login_input_fields
     *
     * @param bool $hide_login_input_fields Defines if login fields should be hidden  [Since version 4.13.0]
     *
     * @return $this
     */
    public function setHideLoginInputFields($hide_login_input_fields)
    {
        $this->container['hide_login_input_fields'] = $hide_login_input_fields;

        return $this;
    }

    /**
     * Gets s3_hosts
     *
     * @return string[]
     */
    public function getS3Hosts()
    {
        return $this->container['s3_hosts'];
    }

    /**
     * Sets s3_hosts
     *
     * @param string[] $s3_hosts List of S3 Hosts  [Since version 4.14.4]
     *
     * @return $this
     */
    public function setS3Hosts($s3_hosts)
    {
        $this->container['s3_hosts'] = $s3_hosts;

        return $this;
    }

    /**
     * Gets auth_methods
     *
     * @return \Swagger\Client\Model\AuthMethod[]
     */
    public function getAuthMethods()
    {
        return $this->container['auth_methods'];
    }

    /**
     * Sets auth_methods
     *
     * @param \Swagger\Client\Model\AuthMethod[] $auth_methods `DEPRECATED`: Authentication methods: * `sql` * `active_directory` * `radius` * `openid` use `authData` instead  [Deprecated since version 4.13.0]
     *
     * @return $this
     */
    public function setAuthMethods($auth_methods)
    {
        $this->container['auth_methods'] = $auth_methods;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


