<?php
/**
 * UpdateAuthTokenRestrictions
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DRACOON
 *
 * REST Web Services for DRACOON<br>Version: 4.14.4  - built at: 2019-11-04 11:46:45<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a>
 *
 * OpenAPI spec version: 4.14.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * UpdateAuthTokenRestrictions Class Doc Comment
 *
 * @category Class
 * @description Request model for updating auth token settings
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UpdateAuthTokenRestrictions implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'UpdateAuthTokenRestrictions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'overwrite_enabled' => 'bool',
        'access_token_validity' => 'int',
        'refresh_token_validity' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'overwrite_enabled' => null,
        'access_token_validity' => 'int32',
        'refresh_token_validity' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'overwrite_enabled' => 'overwriteEnabled',
        'access_token_validity' => 'accessTokenValidity',
        'refresh_token_validity' => 'refreshTokenValidity'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'overwrite_enabled' => 'setOverwriteEnabled',
        'access_token_validity' => 'setAccessTokenValidity',
        'refresh_token_validity' => 'setRefreshTokenValidity'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'overwrite_enabled' => 'getOverwriteEnabled',
        'access_token_validity' => 'getAccessTokenValidity',
        'refresh_token_validity' => 'getRefreshTokenValidity'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['overwrite_enabled'] = isset($data['overwrite_enabled']) ? $data['overwrite_enabled'] : null;
        $this->container['access_token_validity'] = isset($data['access_token_validity']) ? $data['access_token_validity'] : null;
        $this->container['refresh_token_validity'] = isset($data['refresh_token_validity']) ? $data['refresh_token_validity'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['overwrite_enabled'] === null) {
            $invalidProperties[] = "'overwrite_enabled' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets overwrite_enabled
     *
     * @return bool
     */
    public function getOverwriteEnabled()
    {
        return $this->container['overwrite_enabled'];
    }

    /**
     * Sets overwrite_enabled
     *
     * @param bool $overwrite_enabled Defines if OAuth token restrictions are enabled
     *
     * @return $this
     */
    public function setOverwriteEnabled($overwrite_enabled)
    {
        $this->container['overwrite_enabled'] = $overwrite_enabled;

        return $this;
    }

    /**
     * Gets access_token_validity
     *
     * @return int
     */
    public function getAccessTokenValidity()
    {
        return $this->container['access_token_validity'];
    }

    /**
     * Sets access_token_validity
     *
     * @param int $access_token_validity Restricted OAuth access token validity (in seconds)
     *
     * @return $this
     */
    public function setAccessTokenValidity($access_token_validity)
    {
        $this->container['access_token_validity'] = $access_token_validity;

        return $this;
    }

    /**
     * Gets refresh_token_validity
     *
     * @return int
     */
    public function getRefreshTokenValidity()
    {
        return $this->container['refresh_token_validity'];
    }

    /**
     * Sets refresh_token_validity
     *
     * @param int $refresh_token_validity Restricted OAuth refresh token validity (in seconds)
     *
     * @return $this
     */
    public function setRefreshTokenValidity($refresh_token_validity)
    {
        $this->container['refresh_token_validity'] = $refresh_token_validity;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


