<?php
/**
 * GeneralSettingsInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DRACOON
 *
 * REST Web Services for DRACOON<br>Version: 4.14.4  - built at: 2019-11-04 11:46:45<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a>
 *
 * OpenAPI spec version: 4.14.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GeneralSettingsInfoTest Class Doc Comment
 *
 * @category    Class
 * @description General settings
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GeneralSettingsInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GeneralSettingsInfo"
     */
    public function testGeneralSettingsInfo()
    {
    }

    /**
     * Test attribute "share_password_sms_enabled"
     */
    public function testPropertySharePasswordSmsEnabled()
    {
    }

    /**
     * Test attribute "crypto_enabled"
     */
    public function testPropertyCryptoEnabled()
    {
    }

    /**
     * Test attribute "email_notification_button_enabled"
     */
    public function testPropertyEmailNotificationButtonEnabled()
    {
    }

    /**
     * Test attribute "eula_enabled"
     */
    public function testPropertyEulaEnabled()
    {
    }

    /**
     * Test attribute "weak_password_enabled"
     */
    public function testPropertyWeakPasswordEnabled()
    {
    }

    /**
     * Test attribute "use_s3_storage"
     */
    public function testPropertyUseS3Storage()
    {
    }

    /**
     * Test attribute "s3_tags_enabled"
     */
    public function testPropertyS3TagsEnabled()
    {
    }

    /**
     * Test attribute "home_rooms_active"
     */
    public function testPropertyHomeRoomsActive()
    {
    }

    /**
     * Test attribute "home_room_parent_id"
     */
    public function testPropertyHomeRoomParentId()
    {
    }

    /**
     * Test attribute "media_server_enabled"
     */
    public function testPropertyMediaServerEnabled()
    {
    }
}
