<?php
/**
 * OAuthClientTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DRACOON
 *
 * REST Web Services for DRACOON<br>Version: 4.14.4  - built at: 2019-11-04 11:46:45<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a>
 *
 * OpenAPI spec version: 4.14.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OAuthClientTest Class Doc Comment
 *
 * @category    Class
 * @description OAuth client information
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OAuthClientTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OAuthClient"
     */
    public function testOAuthClient()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "client_secret"
     */
    public function testPropertyClientSecret()
    {
    }

    /**
     * Test attribute "client_name"
     */
    public function testPropertyClientName()
    {
    }

    /**
     * Test attribute "client_type"
     */
    public function testPropertyClientType()
    {
    }

    /**
     * Test attribute "is_standard"
     */
    public function testPropertyIsStandard()
    {
    }

    /**
     * Test attribute "is_enabled"
     */
    public function testPropertyIsEnabled()
    {
    }

    /**
     * Test attribute "grant_types"
     */
    public function testPropertyGrantTypes()
    {
    }

    /**
     * Test attribute "redirect_uris"
     */
    public function testPropertyRedirectUris()
    {
    }

    /**
     * Test attribute "access_token_validity"
     */
    public function testPropertyAccessTokenValidity()
    {
    }

    /**
     * Test attribute "refresh_token_validity"
     */
    public function testPropertyRefreshTokenValidity()
    {
    }
}
