<?php
/**
 * PublicUploadShareTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DRACOON
 *
 * REST Web Services for DRACOON<br>Version: 4.14.4  - built at: 2019-11-04 11:46:45<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a>
 *
 * OpenAPI spec version: 4.14.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PublicUploadShareTest Class Doc Comment
 *
 * @category    Class
 * @description Upload Share information
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PublicUploadShareTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PublicUploadShare"
     */
    public function testPublicUploadShare()
    {
    }

    /**
     * Test attribute "is_protected"
     */
    public function testPropertyIsProtected()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "max_slots"
     */
    public function testPropertyMaxSlots()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "is_encrypted"
     */
    public function testPropertyIsEncrypted()
    {
    }

    /**
     * Test attribute "expire_at"
     */
    public function testPropertyExpireAt()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "uploaded_files"
     */
    public function testPropertyUploadedFiles()
    {
    }

    /**
     * Test attribute "user_user_public_key_list"
     */
    public function testPropertyUserUserPublicKeyList()
    {
    }

    /**
     * Test attribute "show_uploaded_files"
     */
    public function testPropertyShowUploadedFiles()
    {
    }

    /**
     * Test attribute "remaining_size"
     */
    public function testPropertyRemainingSize()
    {
    }

    /**
     * Test attribute "remaining_slots"
     */
    public function testPropertyRemainingSlots()
    {
    }

    /**
     * Test attribute "creator_name"
     */
    public function testPropertyCreatorName()
    {
    }

    /**
     * Test attribute "creator_username"
     */
    public function testPropertyCreatorUsername()
    {
    }

    /**
     * Test attribute "max_size"
     */
    public function testPropertyMaxSize()
    {
    }
}
