<?php
/**
 * UpdateUploadShareRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DRACOON
 *
 * REST Web Services for DRACOON<br>Version: 4.14.4  - built at: 2019-11-04 11:46:45<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a>
 *
 * OpenAPI spec version: 4.14.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UpdateUploadShareRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Request model for updating an Upload Share
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateUploadShareRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UpdateUploadShareRequest"
     */
    public function testUpdateUploadShareRequest()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
    }

    /**
     * Test attribute "expiration"
     */
    public function testPropertyExpiration()
    {
    }

    /**
     * Test attribute "files_expiry_period"
     */
    public function testPropertyFilesExpiryPeriod()
    {
    }

    /**
     * Test attribute "internal_notes"
     */
    public function testPropertyInternalNotes()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "show_creator_name"
     */
    public function testPropertyShowCreatorName()
    {
    }

    /**
     * Test attribute "show_creator_username"
     */
    public function testPropertyShowCreatorUsername()
    {
    }

    /**
     * Test attribute "notify_creator"
     */
    public function testPropertyNotifyCreator()
    {
    }

    /**
     * Test attribute "show_uploaded_files"
     */
    public function testPropertyShowUploadedFiles()
    {
    }

    /**
     * Test attribute "max_slots"
     */
    public function testPropertyMaxSlots()
    {
    }

    /**
     * Test attribute "max_size"
     */
    public function testPropertyMaxSize()
    {
    }

    /**
     * Test attribute "text_message_recipients"
     */
    public function testPropertyTextMessageRecipients()
    {
    }

    /**
     * Test attribute "receiver_language"
     */
    public function testPropertyReceiverLanguage()
    {
    }

    /**
     * Test attribute "default_country"
     */
    public function testPropertyDefaultCountry()
    {
    }

    /**
     * Test attribute "reset_password"
     */
    public function testPropertyResetPassword()
    {
    }

    /**
     * Test attribute "reset_files_expiry_period"
     */
    public function testPropertyResetFilesExpiryPeriod()
    {
    }

    /**
     * Test attribute "reset_max_slots"
     */
    public function testPropertyResetMaxSlots()
    {
    }

    /**
     * Test attribute "reset_max_size"
     */
    public function testPropertyResetMaxSize()
    {
    }
}
