<?php
/**
 * ConfigApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DRACOON
 *
 * REST Web Services for DRACOON<br>Version: 4.14.4  - built at: 2019-11-04 11:46:45<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a>
 *
 * OpenAPI spec version: 4.14.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ConfigApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConfigApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getGeneralSettingsInfo
     *
     * Get general settings.
     *
     */
    public function testGetGeneralSettingsInfo()
    {
    }

    /**
     * Test case for getInfrastructurePropertiesInfo
     *
     * Get infrastructure properties.
     *
     */
    public function testGetInfrastructurePropertiesInfo()
    {
    }

    /**
     * Test case for getPasswordPoliciesConfigInfo
     *
     * Get password policies 🞂 NEW 🞀.
     *
     */
    public function testGetPasswordPoliciesConfigInfo()
    {
    }

    /**
     * Test case for getS3TagsInfo
     *
     * Get list of configured S3 tags.
     *
     */
    public function testGetS3TagsInfo()
    {
    }

    /**
     * Test case for getSystemDefaultsInfo
     *
     * Get default values.
     *
     */
    public function testGetSystemDefaultsInfo()
    {
    }

    /**
     * Test case for getSystemSettings
     *
     * Get system settings.
     *
     */
    public function testGetSystemSettings()
    {
    }

    /**
     * Test case for setSystemSetting
     *
     * Change system settings.
     *
     */
    public function testSetSystemSetting()
    {
    }
}
