<?php
/**
 * GroupsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DRACOON
 *
 * REST Web Services for DRACOON<br>Version: 4.14.4  - built at: 2019-11-04 11:46:45<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a>
 *
 * OpenAPI spec version: 4.14.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * GroupsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GroupsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addGroupMembers
     *
     * Add group members.
     *
     */
    public function testAddGroupMembers()
    {
    }

    /**
     * Test case for createGroup
     *
     * Create new user group.
     *
     */
    public function testCreateGroup()
    {
    }

    /**
     * Test case for deleteGroup
     *
     * Delete user group.
     *
     */
    public function testDeleteGroup()
    {
    }

    /**
     * Test case for deleteGroupMembers
     *
     * Remove group members.
     *
     */
    public function testDeleteGroupMembers()
    {
    }

    /**
     * Test case for getGroup
     *
     * Get user group.
     *
     */
    public function testGetGroup()
    {
    }

    /**
     * Test case for getGroupRoles
     *
     * Get list of roles assigned to the group.
     *
     */
    public function testGetGroupRoles()
    {
    }

    /**
     * Test case for getGroupRooms
     *
     * Get rooms granted to the group or / and rooms that can be granted.
     *
     */
    public function testGetGroupRooms()
    {
    }

    /**
     * Test case for getGroupUsers
     *
     * Get group member users or / and users who can become a member.
     *
     */
    public function testGetGroupUsers()
    {
    }

    /**
     * Test case for getGroups
     *
     * Get list of user groups.
     *
     */
    public function testGetGroups()
    {
    }

    /**
     * Test case for getLastAdminRoomsGroups
     *
     * Get rooms where the group is defined as last admin group.
     *
     */
    public function testGetLastAdminRoomsGroups()
    {
    }

    /**
     * Test case for updateGroup
     *
     * Update user group's metadata.
     *
     */
    public function testUpdateGroup()
    {
    }
}
